= Curriculum
Jose Henrique Ventura
2019-01-13
:jbake-type: post
:jbake-status: published
:jbake-tags: my cv, Jose Henrique Ventura
:idprefix:

=== Summary

Self-motivated person with seven years of hands-on experience in development of enterprise applications with specialization
in Java/Java EE. During these years, I have been following technologies which surround the Java ecosystem to create the
applications with a high level of quality, security and availability.

=== Experience timeline

*Contributions to Open Source projects* +

*Project:* http://tomee.apache.org[Apache Tomee] - *MicroProfile* examples +

* MicroProfile - http://tomee.apache.org/tomee-8.0/examples/mp-custom-healthcheck.html[FaultTolerance @Retry] - https://github.com/apache/tomee/pull/260[#260]
* MicroProfile - http://tomee.apache.org/tomee-8.0/examples/mp-faulttolerance-retry.html[Custom Health Check] - https://github.com/apache/tomee/pull/302[#302]

---

*Company:* WorldNet TPS +
*Role:* Software Engineer +
*Date:* Since July of 2015 +
*Location:* Ireland, Dublin. +

Working as a Java Team Leader & Software Developer with such technologies: +

* GlassFish, WildFly, Java EE, Java 8, MySQL Server, REST, WebService, Apache Ant, Redmine, Intellij.
* Integrating the Payment Gateway with Acquires and Processors. +
* Performing code reviews of co-worker’s deliverable to ensure best practices, quality and security,
including suggestions of refactor making the code clear and legible. +

---

*Company:* CasBrazil - Pharmaceutical Consultant  (Remote Mostly) +
*Role:* Software Engineer +
*Date:* 01/2014 - 10/2017 +
*Location:* Campinas, São Paulo - Brazil. +

* Worked mostly in converting tools designed firstly with Excel Spreadsheets into Webapp's. +
* Design of APIs which handle batch files/data of Costumers. +
* Design of services which handled a reasonable quantity of large files daily of Costumers where reports are created to explain to the Customer the situation of the content. +
* Configured instances initially in Amazon AWS and after a long time moving them to Google Could Computer. Instances to run Java Applications, Nginx and PostgresSql. +

---

*Project:* SIGGA ­ Geographic Information System to Support Environmental - Government and Public Sector +
*Role:* Software Developer (Freelancer) +
*Date:* 2013 - 2014 +
*Location:* Campinas, São Paulo - Brazil. +

* The transposition of the São Francisco River is part of displacement design of the waters of the São Francisco River in Brazil,
 appointed by the Brazilian government as "Integration Project of the São Francisco River Watershed with the Northern Northeast".

* Activities +
** System and Database modeling
** Analyze of requirements and documentation.
** Development of a system to track where such activities happens as deforestation, plantation of new trees among other things
based on coordinates.

* Technologies
** Integration with 3Geo map, Java 6, JSF 2.0, Richfaces 3.x, Tomcat 7, Spring Security 3.1, Postgresql with PostGis extension.
and SVN for version control.

---

*Company:* CPqD - IT and Telecommunications Service Provider https://www.cpqd.com.br/en/[https://www.cpqd.com.br/en/] +
*Role:* Analyst Support level III +
*Date:* 2013 - 2014 +
*Location:* Campinas, São Paulo - Brazil. +

* As support analyst I was able to give maintenance to critical points of the system and propose solutions to the client in
a timely manner. Interacting with support level II and clients it gave another point of view of how customer use the system
where I could report possible improvements of usability and performance of algorithms with a large set of data.

---

*Company:* CPqD - IT and Telecommunications Service Provider https://www.cpqd.com.br/en/[https://www.cpqd.com.br/en/] +
*Role:* System Analyst +
*Date:* 2011 - 2013 +
*Location:* Campinas, São Paulo - Brazil. +

* I was able to develop more complex business rules using JEE (EJB, JPA) and bug corrections where it was necessary to identify
the problem and propose a solution for improvements. At this stage I learned how to examine related performance problems,
algorithms and database operations that were slow.

---

*Company:* CPqD - IT and Telecommunications Service Provider https://www.cpqd.com.br/en/[https://www.cpqd.com.br/en/] +
*Role:* Intern +
*Date:* 2010 - 2011 +
*Location:* Campinas, São Paulo - Brazil. +

* As an intern, I had to deal with algorithms using the programing language Java, PL/SQL for Oracle database and
merging branches to better understand the team workflow.

---

=== Education

*Title:* Bachelor's Degree in Computer Science +
*Institution:* Universidade Paulista +
*Location:* Campinas, São Paulo - Brazil +
*Year:* 2009 - 2013

=== Certification

*Title:* OCP (_Oracle Certification Program_) - Java 6 +
*Date:* January 2011 +

=== Professional Memberships/Awards

*Title:* Ulster Bank Hackathon +
*Project:* GoDutch Project +
*Location:* Ireland, Dublin. +
*Year:* 2016 +
*Publication*: https://irishtechnews.ie/ideas-around-going-dutch-childrens-finance-and-alternative-banking-cards-take-prizes-at-ulster-bank-hackathon/[Irish Tech News] +
*Description:* The aiming of the project was to solve an issue that most of people have when the hangout together and
they need to slit the bill by what each person have consumed.
*Technologies:*

* Android/IOS
* WildFLy (Hosting JSF pages, WebSockets and in-memory database Infinispan)
* Postgres database
* https://www.openbankproject.com/[Open Bank API] for payment integration.

==== Skills with the following technologies

GlassFish, WildFly (Swarm/Thorntail for Microservices), Tomcat, Nginx +
HAProxy, Consul +
Java 6+, JavaScript +
Eclipse IDE, Git, Subversion +
MySQL, PostgresSQL, Oracle +
Apache Ant, Apache Maven +
Jenkins +
SonarLint +
JIRA, Redmine, Trello +
Mac OS X, Linux and Windows +
Jenkins, Travis +
JSF, JSP, WebSockets, Angular 4 +
